### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by mobius07** [Cvar1984/sqlscan#1]
Hello.

I set all as described in the Kali and error appears:

`root@kali:~# sqlscan http://demo.testfire.net`
`PHP Fatal error:  Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/sqlscan" in /usr/local/bin/sqlscan:9`
`Stack trace:`
`#0 /usr/local/bin/sqlscan(9): Phar::webPhar(NULL, 'index.php')`
`#1 {main}`
`  thrown in /usr/local/bin/sqlscan on line 9`

![123](https://user-images.githubusercontent.com/20757829/69935975-002c1780-1509-11ea-81e7-4514f55df540.png)

**Comment by Cvar1984** [comment]
> Hello.
> 
> I set all as described in the Kali and error appears:
> 
> `root@kali:~# sqlscan http://demo.testfire.net`
> `PHP Fatal error: Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/sqlscan" in /usr/local/bin/sqlscan:9`
> `Stack trace:`
> `#0 /usr/local/bin/sqlscan(9): Phar::webPhar(NULL, 'index.php')`
> `#1 {main}`
> ` thrown in /usr/local/bin/sqlscan on line 9`
> 
> ![123](https://user-images.githubusercontent.com/20757829/69935975-002c1780-1509-11ea-81e7-4514f55df540.png)

this tools need some php extension called _php-bz2_
You can install it using _apt_, _pecl_, or compile it manually
[here](https://stackoverflow.com/questions/24988022/php-enable-bz2-extension-in-php-ini)

**Comment by mobius07** [comment]
Thank you, it worked.
