### ISSUE TITLE
[PHP] Progress Bar Fatal Error

### ISSUE THREAD

**Issue by ghost** [Cvar1984/sqlscan#2]
After `[#] Total available urls : (any number)`
It runs the progress bar (https://packagist.org/packages/guiguiboy/php-cli-progress-bar).

However, results in fatal error (mb_strlen)

Should make this issue more visible.

```
PHP Fatal error:  Uncaught Error: Call to undefined function ProgressBar\mb_strlen() in phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php:186
Stack trace:
#0 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(169): ProgressBar\Manager->clearRightCharacters()
#1 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(219): ProgressBar\Manager->display()
#2 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(227): ProgressBar\Manager->update()
#3 phar:///usr/local/bin/sqlscan/src/SqlScan.php(55): ProgressBar\Manager->advance()
#4 phar:///usr/local/bin/sqlscan/main.php(24): Cvar1984\SqlScan\SqlScan->scan()
#5 /usr/local/bin/sqlscan(10): require('phar:///usr/loc...')
#6 {main}
  thrown in phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php on line 186
```

**Comment by Cvar1984** [comment]
> Hi,
> Whenever I get "[#] Total available urls : (any number)", it runs the Progress Bar (https://packagist.org/packages/guiguiboy/php-cli-progress-bar).
> 
> However, results in fatal error.
> Any good solutions to this?
> 
> ```
> PHP Fatal error:  Uncaught Error: Call to undefined function ProgressBar\mb_strlen() in phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php:186
> Stack trace:
> #0 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(169): ProgressBar\Manager->clearRightCharacters()
> #1 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(219): ProgressBar\Manager->display()
> #2 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(227): ProgressBar\Manager->update()
> #3 phar:///usr/local/bin/sqlscan/src/SqlScan.php(55): ProgressBar\Manager->advance()
> #4 phar:///usr/local/bin/sqlscan/main.php(24): Cvar1984\SqlScan\SqlScan->scan()
> #5 /usr/local/bin/sqlscan(10): require('phar:///usr/loc...')
> #6 {main}
>   thrown in phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php on line 186
> ```

The function mb_strlen() is not enabled by default in PHP. Please read the manual for installation details:

http://www.php.net/manual/en/mbstring.installation.php

**Comment by ghost** [comment]
> > Hi,
> > Whenever I get "[#] Total available urls : (any number)", it runs the Progress Bar (https://packagist.org/packages/guiguiboy/php-cli-progress-bar).
> > However, results in fatal error.
> > Any good solutions to this?
> > ```
> > PHP Fatal error:  Uncaught Error: Call to undefined function ProgressBar\mb_strlen() in phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php:186
> > Stack trace:
> > #0 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(169): ProgressBar\Manager->clearRightCharacters()
> > #1 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(219): ProgressBar\Manager->display()
> > #2 phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php(227): ProgressBar\Manager->update()
> > #3 phar:///usr/local/bin/sqlscan/src/SqlScan.php(55): ProgressBar\Manager->advance()
> > #4 phar:///usr/local/bin/sqlscan/main.php(24): Cvar1984\SqlScan\SqlScan->scan()
> > #5 /usr/local/bin/sqlscan(10): require('phar:///usr/loc...')
> > #6 {main}
> >   thrown in phar:///usr/local/bin/sqlscan/vendor/guiguiboy/php-cli-progress-bar/ProgressBar/Manager.php on line 186
> > ```
> 
> The function mb_strlen() is not enabled by default in PHP. Please read the manual for installation details:
> 
> http://www.php.net/manual/en/mbstring.installation.php

Thank you.
