### ISSUE TITLE
Cannot find '.txt' file with extracted urls

### ISSUE THREAD

**Issue by 30Sana** [Cvar1984/sqlscan#6]
I cannot find the .txt file but the script seems to be running fine. 👍 

**Screenshots**
![image](https://user-images.githubusercontent.com/93611007/191114858-175087e2-11c6-40aa-b873-df0784f4cef6.png)

**Environment:**
 - Kali Linux Through Windows 10

**Comment by Cvar1984** [comment]
the program will automaticly write result into txt file, if there is no txt file it mean you have no result. this tools is abandoned get something real like owasp zap
